// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJp_7NnthBLuFoYmYEIo0l8eOoqg-NK04',
    appId: '1:330649638411:web:ed2925d9d2f85a9ed5d90e',
    messagingSenderId: '330649638411',
    projectId: 'bkl-messanger',
    authDomain: 'bkl-messanger.firebaseapp.com',
    storageBucket: 'bkl-messanger.firebasestorage.app',
    measurementId: 'G-1PJ7XGW87F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfsKpwWxATJt_GM5pGTyzK0Vt8Fv96dEM',
    appId: '1:330649638411:android:5261282d97856c61d5d90e',
    messagingSenderId: '330649638411',
    projectId: 'bkl-messanger',
    storageBucket: 'bkl-messanger.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2AtJeehFC0Ev0FOcsj67G4i0kvNrz4Hk',
    appId: '1:330649638411:ios:f2949ed4c12a92c8d5d90e',
    messagingSenderId: '330649638411',
    projectId: 'bkl-messanger',
    storageBucket: 'bkl-messanger.firebasestorage.app',
    iosBundleId: 'com.example.bklMessanger',
  );
}
